### ISSUE TITLE
Any chance it'll work on Extreme?

### ISSUE THREAD

**Issue by hawkefrc03** [StrongMods/StrongMod#3]
First of all, i greatly thank you for creating this mod, and it works fine on my game on Steam. 

By the way, will you add another version that could work on Stronghold Crusader Extreme? Much appreciated 🙏

**Comment by StrongMods** [comment]
Thank you for your kind words!
The addresses are hardcoded, which makes it quite challenging. Creating two versions would make it harder to update in the future, although I might not update it.

**Comment by hawkefrc03** [comment]
is it possible tho?

**Comment by StrongMods** [comment]
Now it should work on extreme.

**Comment by hawkefrc03** [comment]
AWH YASSS, Thx for updating it man, it works perfectly fine. :D
